#!/bin/bash
set -e

if [ "$EUID" -ne 0 ]; then
  echo "Bitte als root oder mit sudo ausführen."
  exit 1
fi

apt-get update && apt-get upgrade -y
apt-get install -y openssh-server firefox-esr cage fonts-open-sans iputils-ping

if ! id "cage" &>/dev/null; then
    useradd -m -G video,render -s /bin/bash cage
else
    echo "Nutzer existiert bereits."
fi

#
# Quelle: https://github.com/cage-kiosk/cage/wiki/Starting-Cage-on-boot-with-systemd
#
cat <<'EOF' > /etc/pam.d/cage
auth           required        pam_unix.so nullok
account        required        pam_unix.so
session        required        pam_unix.so
session        required        pam_systemd.so
EOF

cat <<'EOF' > /etc/systemd/system/cage@.service
# This is a system unit for launching Cage with auto-login as the
# user configured here. For this to work, wlroots must be built
# with systemd logind support.

[Unit]
Description=Cage Wayland compositor on %I
# Make sure we are started after logins are permitted. If Plymouth is
# used, we want to start when it is on its way out.
After=systemd-user-sessions.service plymouth-quit-wait.service
# Since we are part of the graphical session, make sure we are started
# before it is complete.
Before=graphical.target
# On systems without virtual consoles, do not start.
ConditionPathExists=/dev/tty0
# D-Bus is necessary for contacting logind, which is required.
Wants=dbus.socket systemd-logind.service network-online.target
After=dbus.socket systemd-logind.service network-online.target
# Replace any (a)getty that may have spawned, since we log in
# automatically.
Conflicts=getty@%i.service
After=getty@%i.service

[Service]
Type=simple
Environment=WLR_LIBINPUT_NO_DEVICES=1
Environment=MOZ_ENABLE_WAYLAND=1
ExecStartPre=/bin/sh -c 'until ping -c1 -W2 jonahhain.github.io >/dev/null 2>&1; do sleep 1; done'
ExecStart=/usr/bin/cage -d -s /usr/bin/firefox -- --kiosk https://jonahhain.github.io/stundenplan/
ExecStartPost=+sh -c "tty_name='%i'; exec chvt $${tty_name#tty}"
Restart=always
RestartSec=5
User=cage
# Log this user with utmp, letting it show up with commands 'w' and
# 'who'. This is needed since we replace (a)getty.
UtmpIdentifier=%I
UtmpMode=user
# A virtual terminal is needed.
TTYPath=/dev/%I
TTYReset=yes
TTYVHangup=yes
TTYVTDisallocate=yes
# Fail to start if not controlling the virtual terminal.
StandardInput=tty-fail

# Set up a full (custom) user session for the user, required by Cage.
PAMName=cage

[Install]
WantedBy=graphical.target
DefaultInstance=tty7
EOF

systemctl daemon-reload
systemctl enable cage@tty1.service
systemctl set-default graphical.target

echo "--- Fertig! ---"
echo "Bitte neu starten."
